# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dataHaskell
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  DataHaskell is an open-source organization devoted to enabling
  reliable and reproducible data science and machine learning by 
  leveraging the Haskell programming language. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://datahaskell.org" # the base hostname & protocol for your site
twitter_username: datahaskell
github_username:  dataHaskell

# Build settings
markdown: kramdown
